ALTER TABLE assessments ADD COLUMN IF NOT EXISTS option_a TEXT NOT NULL;
ALTER TABLE assessments ADD COLUMN IF NOT EXISTS option_b TEXT NOT NULL;
ALTER TABLE assessments ADD COLUMN IF NOT EXISTS option_c TEXT NOT NULL;
ALTER TABLE assessments ADD COLUMN IF NOT EXISTS option_d TEXT NOT NULL;